name: Update News

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: node bot/fetchNews.js
